### ISSUE TITLE
Error running in WebdriverIO Sync mode

### ISSUE THREAD

**Issue by klamping** [applitools/eyes.webdriverio.javascript#24]
In the latest version (1.1.2), I get the following error when running inside the wdio test runner using sync mode:

```
this.remoteWebDriver.execute(...).then is not a function
running firefox
TypeError: this.remoteWebDriver.execute(...).then is not a function
    at EyesWebDriver.getUserAgent (/Users/klamping/Sites/wdio-applitools-demo/node_modules/@applitools/eyes.webdriverio/src/wrappers/EyesWebDriver.js:147:71)
    at Eyes.open (/Users/klamping/Sites/wdio-applitools-demo/node_modules/@applitools/eyes.webdriverio/src/Eyes.js:151:25)
    at Context.<anonymous> (/Users/klamping/Sites/wdio-applitools-demo/test/specs/visual.js:13:18)
    at /Users/klamping/Sites/wdio-applitools-demo/node_modules/wdio-sync/build/index.js:590:26
    at new Promise (<anonymous>)
    at new F (/Users/klamping/Sites/wdio-applitools-demo/node_modules/core-js/library/modules/_export.js:36:28)
    at Context.executeSync (/Users/klamping/Sites/wdio-applitools-demo/node_modules/wdio-sync/build/index.js:588:12)
    at /Users/klamping/Sites/wdio-applitools-demo/node_modules/wdio-sync/build/index.js:759:42
```

Example code with failure is here:
https://github.com/klamping/test-app-wdio

I can confirm this code works with v1.1.0

**Comment by aaronwilliams1** [comment]
I saw this today too. 

But if I use an older version I get batches stuck at RUNNING. So blocked. :(

**Comment by adityaarakeri** [comment]
I see this error using chrome:

```this.remoteWebDriver.execute(...).then is not a function
running chrome
TypeError: this.remoteWebDriver.execute(...).then is not a function
    at EyesWebDriver.getUserAgent (/Users/Aditya/Retail-Automation/applitools/node_modules/@applitools/eyes.webdriverio/src/wrappers/EyesWebDriver.js:147:71)
    at Eyes.open (/Users/Aditya/Retail-Automation/applitools/node_modules/@applitools/eyes.webdriverio/src/Eyes.js:151:25)
    at Context.<anonymous> (/Users/Aditya/Retail-Automation/applitools/spec/test.js:78:18)
    at Promise.F (/Users/Aditya/Retail-Automation/applitools/node_modules/core-js/library/modules/_export.js:36:28)```

**Comment by klamping** [comment]
For those facing this issue, you should be able to avoid it by installing v1.1.0:
`npm install @applitools/eyes.webdriverio@1.1.0 --save-dev --save-exact`

**Comment by platinumtest** [comment]
Installing the exact version of @applitools/eyes.webdriverio worked. It was frustrating attempting to run the sample webdriver.io /applitools  script and watch it fail over and over again for the last 2 days without figuring out why this was happening.  Thanks for the workaround!

**Comment by danielputerman** [comment]
Hi all, thanks. This is fixed in [version 1.2.0](https://github.com/applitools/eyes.webdriverio.javascript/releases/tag/v1.2.0)
